### PR TITLE
replace clj-stacktrace with aviso/pretty - follow up on #77

### PR DESCRIPTION
**Pull request by carocad**
Hey guys,
there are several things on this pull request that I would like to discuss. 
- Currently only the collapsible-exception behavior uses colors for the stacktraces, should the normal behavior also have them?
- I found out that in some cases the exception summaries can be quite long so I added the truncation for all summaries
- the `strip-ansi` function is intentionally duplicated in clojure.cljs and collapsible_exception.cljs since I don't know which one is going to stay on the long run.
- In the lein-light-nrepl I could see that you trim some parts of the stacktrace. I personally trim away the parts below, but I don't know if this should always be done or rather be a user specific stuff.

```
(def lighttable-internals
  #{#"lighttable\.nrepl\.eval"
    #"lighttable\.nrepl\.core"
    #"clojure\.tools\.nrepl\.middleware\.interruptible-eval"})
```
- I'm not a CSS/designer expert so I mostly used the defaults colors from ansi; with two notable exceptions, "red" -> "OrangeRed" and "green" -> "limegreen", since it was quite difficult to read those on the pink stacktrace-background that Lighttable uses for exceptions. Any ideas here?

### CODE REVIEW

**Comment by cldwalker** [comment]
Hi @carocad. Thanks for the suggested feature. I think aviso is a great library but is something that should be chosen per project, not as a default for all editor users. If @kenny-evitt and @rundis disagree, want this behavior and are willing to review and maintain this, I'm open to it if the following two issues are addressed:

1. Making aviso an optional behavior: Most intermediate and advanced Clojure users like to choose their stacktrace tool per project, if they use one at all. clj-stacktrace has been an acceptable tool for these users as it is considered a lightweight, battle-tested library. We should have a behavior that changes the nrepl middleware behavior such that `lighttable.nrepl.exception/clean-trace` points to aviso instead of clj-stacktrace. With this behavior, we can allow for beginner-friendly stacktraces while not turning away intermediate and advanced users from LT.
2. aviso is an extra dependency to our nrepl lib. We have gone to great effort to make the nrepl lib as minimal as possible because of issues like #48. With aviso as an additional dependency, we'll need to verify that projects that use a different version of aviso or a different version of [clojure.tools.logging](https://github.com/AvisoNovate/pretty/blob/ce21157bc07176a23bf4f020173ce7c48ab22d63/project.clj#L7) are able to eval without issues seen in #48

**Comment by carocad** [comment]
hey @cldwalker 
I understand your concerns, although I didn't see those coming. Thus I have a counter proposal :)

>  I think aviso is a great library but is something that should be chosen per project, not as a default for all editor users.

Well currently clj-stacktrace is the only option for all editor users so this doesn't seen to fair with everyone. Since clj-stacktrace/pretty functions are directly used by `clean-trace` we would always be constrained to choose which stacktrace formating would be best for all users (please correct me if I'm wrong). I have tried to use pretty as a plugin or even calling `(pst)` from Lighttable but since the exceptions are catch in `lein-light-nrepl` that was useless.

So my proposal is the following:
- replace `(clean-trace e)` with `(with-out-str (clojure.repl/pst e))`. This would let every user choose their own stacktrace formating tool and free us from having to care about it. Both `clj-stacktrace` (see [here](https://github.com/mmcgrana/clj-stacktrace/blob/master/src/leiningen/hooks/clj_stacktrace_test.clj#L15)) and `pretty` (see [here](https://github.com/AvisoNovate/pretty/blob/master/src/io/aviso/repl.clj#L60)) have leiningen hooks that replace `clojure.repl/pst` thus it shouldn't be a problem. (I have tested this on my repl and it works; I have yet to try it on `lein-light-nrepl`). 

- add a `:stack-mini` or `:stack-lt` keyword to the messages sent from `lein-light-nrepl` to the clojure plugin. Something like `:stack-lt (clean-trace e)`. This way the Lighttable team could provide a custom stacktrace message which shouldn't get in the way of any other user-selected plugin.

- add a default behavior which would let the user decide if the lighttable custom stacktrace or the  user specific plugin stacktrace message should be displayed. (defaults to lighttable?)

- I have checked `pretty` source code and from what I have seen, the stacktrace processing part shouldn't be more than 300 LOC, which should be ok to adapt (copy?). I would be willing to work on that, but it would probably take some time until I finish it. Thus, I think it would be better to have clj-stacktrace as the default `:stack-lt` in the meantime.

I think this should cover all the points that you mentioned and even leave some room for future development of the Clojure plugin without constraining us to choose what is "best" for everyone (probably impossible to get right).

**Comment by carocad** [comment]
@cldwalker @rundis @kenny-evitt any thoughts on this?

**Comment by kenny-evitt** [comment]
@carocad I can't understand all of this in detail, but your latest suggestion seems reasonable. I defer to both @cldwalker and @rundis about the suitability of those changes tho, so you may want to wait on confirmation from them before doing any more work.

My understanding of our preffered constraints is:

 1. Don't add dependencies to the *nrepl* lib.
 2. Maintain current behavior as a default for any changes that allow different behavior.

You're latest suggestions seem to meet both.

**Comment by carocad** [comment]
closing as I cannot maintain this anymore

**Pull request closed without merging**
