### PR TITLE
sort clojure's doc search by best fit

### PR DESCRIPTION
**Pull request by carocad**
solves Lighttable issue "doc search result not ordered by best match #2048"

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@carocad Thanks for the PR. I'll try to take a look at it soon-ish.

**Comment by sbauer322** [comment]
This seems to work well. It addresses the original use case in https://github.com/LightTable/LightTable/issues/2048. 

For comparison, I have created a [gist](https://gist.github.com/sbauer322/bd8868e2b1e709e6550ce832f41e22ca) that shows some examples comparing our current language doc search to this. To keep it brief, I have limited it to the first 10 results and just the function name.

I have some minor formatting tweaks, which I can currently only address by opening a new PR, but otherwise I wanted to get feedback from @cldwalker or @rundis before merging. 

If no one responds before Nov 1, 2016 then I will proceed with merging via a new PR (due to the formatting tweaks).

**Comment by sbauer322** [comment]
@LightTable/committers - last call for feedback before this will be merged tomorrow!

**Comment by cldwalker** [comment]
@sbauer322 Sounds good. Thanks for the throwing up the comparison

**Comment by sbauer322** [comment]
Anytime! 😄

**Comment by carocad** [comment]
@sbauer322 I am happy to see this moving forward :)

**Comment by sbauer322** [comment]
As mentioned above, I am closing this PR in favor of merging https://github.com/LightTable/Clojure/pull/94 in order to implement some formatting tweaks on this PR.

**Pull request closed without merging**
