### PR TITLE
Delete target/classes before connecting to avoid classpath LT issue 1880

### PR DESCRIPTION
**Pull request by rundis**
A somewhat hacky attempt to address https://github.com/LightTable/LightTable/issues/1880

### CODE REVIEW

**Comment by cldwalker** [comment]
I think the hack is acceptable given how much of an edge case uberjar + connect is. Could we make this configurable via a behavior? We'll also need to pull in `delete-dir` and `directory` into our own fs. As for whether we should make this behavior the default I'm conflicted. Intermediate/advanced users will find this surprising and potentially insidious whereas new users may find this helpful

**Comment by kenny-evitt** [comment]
If we're not going to make this a default, maybe we don't need to do anything. Running *lein clean* after building an uberjar is hardly an unreasonable step to take. I wouldn't expect anyone to be building uberjars frequently. Maybe we can just punt and 'fix' this with a note in docs somewhere.

**Comment by cldwalker** [comment]
Good point. A documentation fix is reasonable

**Comment by rundis** [comment]
I never really liked this hack. I suggest we close this and create a new issue for documentation as @kenny-evitt suggests. The only real fix feels like solving the challenge we have with dependency isolation.

**Comment by kenny-evitt** [comment]
#1971 covers documenting this.

**Pull request closed without merging**
